"""add habit tracker models

Revision ID: 07084100757a
Revises: eb6e326ff609
Create Date: 2026-08-26 02:18:48.308605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07084100757a'
down_revision = 'eb6e326ff609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('frequency_per_week', sa.Integer(), nullable=False),
    sa.Column('measurement_type', sa.String(length=20), nullable=False),
    sa.Column('measurement_unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uq_habit_date')
    )
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_logs_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_logs_date'))

    op.drop_table('habit_logs')
    op.drop_table('habits')
    # ### end Alembic commands ###
