"""add_health_tracker_models

Revision ID: 4ad3de1dc0a4
Revises: 07084100757a
Create Date: 2026-09-11 01:27:35.183887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad3de1dc0a4'
down_revision = '07084100757a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('vision_right', sa.String(length=40), nullable=True),
    sa.Column('vision_left', sa.String(length=40), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurements_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('daily_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.String(length=20), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_health')
    )
    with op.batch_alter_table('daily_health_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_health_logs_date'), ['date'], unique=False)

    op.create_table('diet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('food_items', sa.Text(), nullable=False),
    sa.Column('food_tags', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fats_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_diet_logs_user_id'), ['user_id'], unique=False)

    op.create_table('diet_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('target_protein_g', sa.Float(), nullable=False),
    sa.Column('target_carbs_g', sa.Float(), nullable=False),
    sa.Column('target_fats_g', sa.Float(), nullable=False),
    sa.Column('target_fiber_g', sa.Float(), nullable=False),
    sa.Column('target_water_ml', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.String(length=60), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=20), nullable=False),
    sa.Column('exercises_details', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_logs_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_days_per_week', sa.Integer(), nullable=False),
    sa.Column('target_minutes_per_week', sa.Integer(), nullable=False),
    sa.Column('target_calories_per_week', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('health_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('doctor_visited', sa.Boolean(), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('clinic_hospital', sa.String(length=150), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_issues_user_id'), ['user_id'], unique=False)

    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('lab_name', sa.String(length=120), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('summary_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hemoglobin', sa.Float(), nullable=True),
    sa.Column('wbc_count', sa.Float(), nullable=True),
    sa.Column('rbc_count', sa.Float(), nullable=True),
    sa.Column('platelet_count', sa.Float(), nullable=True),
    sa.Column('hematocrit_pct', sa.Float(), nullable=True),
    sa.Column('total_cholesterol', sa.Float(), nullable=True),
    sa.Column('hdl_cholesterol', sa.Float(), nullable=True),
    sa.Column('ldl_cholesterol', sa.Float(), nullable=True),
    sa.Column('triglycerides', sa.Float(), nullable=True),
    sa.Column('vldl', sa.Float(), nullable=True),
    sa.Column('vitamin_d', sa.Float(), nullable=True),
    sa.Column('vitamin_b12', sa.Float(), nullable=True),
    sa.Column('iron_ferritin', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('blood_sugar_fasting', sa.Float(), nullable=True),
    sa.Column('hba1c', sa.Float(), nullable=True),
    sa.Column('serum_creatinine', sa.Float(), nullable=True),
    sa.Column('uric_acid', sa.Float(), nullable=True),
    sa.Column('sgpt_alt', sa.Float(), nullable=True),
    sa.Column('sgot_ast', sa.Float(), nullable=True),
    sa.Column('tsh', sa.Float(), nullable=True),
    sa.Column('other_findings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reports_test_date'), ['test_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_medical_reports_test_date'))

    op.drop_table('medical_reports')
    with op.batch_alter_table('health_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_issues_user_id'))

    op.drop_table('health_issues')
    op.drop_table('exercise_targets')
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_logs_date'))

    op.drop_table('exercise_logs')
    op.drop_table('diet_targets')
    with op.batch_alter_table('diet_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_diet_logs_date'))

    op.drop_table('diet_logs')
    with op.batch_alter_table('daily_health_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_health_logs_date'))

    op.drop_table('daily_health_logs')
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurements_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_measurements_date'))

    op.drop_table('body_measurements')
    # ### end Alembic commands ###
