"""add habit_type to habits

Revision ID: bb46d1640cea
Revises: 4ad3de1dc0a4
Create Date: 2026-09-29 01:02:22.227059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb46d1640cea'
down_revision = '4ad3de1dc0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habit_type', sa.String(length=20), nullable=False, server_default='positive'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('habit_type')

    # ### end Alembic commands ###
